const CONSTANTS = {
  CASH_IN_COMMISSION_RATE: 0.0003,
  MAX_CASH_IN_COMMISSION: 5,
  CASH_OUT_NATURAL_COMMISSION_RATE: 0.003,
  MIN_CASH_OUT_JURIDICAL_COMMISSION: 0.5,
  CENTS_IN_EUR: 100,
  FREE_WEEKLY_QUOTA: 1000
};

module.exports = CONSTANTS;
